### ISSUE TITLE
question: premium system

### ISSUE THREAD

**Issue by Zarkness** [Iru21/Authy#1]
My question is if the plugin has or will have a way for users to set /premium and login with a premium account without having to set /login password.

**Comment by Iru21** [comment]
This feature is something that has been planned for a long time and I'm still looking into it. So yeah, it will come but no ETA for now

**Comment by Zarkness** [comment]
okay, thank you very much

**Comment by FunkyNico** [comment]
I thinks this can be done with [FastLogin](https://github.com/games647/FastLogin) and it would be great!

**Comment by Zarkness** [comment]
I prefer to have it integrated into the plugin itself rather than having to add a third party plugin. @FunkyNico
