### ISSUE TITLE
HELP! Im so confused!

### ISSUE THREAD

**Issue by PleBruh** [Iru21/Authy#15]
Hey so long story short, nobody can use the commands, dunno where u also do the author.reg perm command too pls my friend had to be op to register and login!

Reply if you need to know plugins we use

**Comment by PleBruh** [comment]
Okay I wanna add; I have essentialsX and that most of it's commands that should be available for non ops aren't like /afk

**Comment by Iru21** [comment]
> You need to give these permissions to your default group - authy.login, authy.register, authy.unregister, authy.remember and authy.pin using a permission plugin (I personally recommend luckperms)

taken from the faq on the discord support server, you just need a permission plugin

**Comment by PleBruh** [comment]
omg youre a life saver! ive fixed every permissions now! have a great day and thx sm!
