### ISSUE TITLE
Issue with teleport on join on multi-world server

### ISSUE THREAD

**Issue by liquidman228** [Iru21/Authy#20]
Hey

When setting teleport location on join, it teleports player to that coordinates but not teleporting to a needed world
So when i quit the server being in the nether or any other world, it teleports me to that coordinates anyway

I am using multiverse-core plugin and have many worlds
And now i am having a problem, where i am underground or inside blocks, when i join the server

Will be great if i could configure a world to teleport on join

**Comment by Iru21** [comment]
will add a configurable world in the next release

**Comment by Iru21** [comment]
fixed in v3.1.3
