### ISSUE TITLE
Can't login inside of portals

### ISSUE THREAD

**Issue by Spejik** [Iru21/Authy#22]
For example, when players get timed out while traveling through nether portals, they can't login after joining back.

We could teleport the player to the nearest position where they can type and then back to where they were.
I know you can enable teleport and back after login, but I don't really trust plugins teleporting me that far and not back, making me walk 4000 blocks. 

I would make a PR but I barely know how plugins are coded so I'll leave it to someone else.

**Comment by Iru21** [comment]
> We could teleport the player to the nearest position where they can type and then back to where they were.

Set `onJoin.concealment` to `true` in the config until I implement a fix.
