### ISSUE TITLE
没有op权限无法注册

### ISSUE THREAD

**Issue by zfxkj** [Iru21/Authy#27]
我在使用时发现在用户没有op权限时，注册命令register 是没有的。
Minecraft版本：1.19.3

**Comment by Iru21** [comment]
下载一个权限插件，将这些权限添加到默认组`authy.login`, `authy.register`, `authy.unregister`, `authy.remember`, `authy.pin`。
(translated with deepl)
> Download a permission plugin and add these permissions to the default group `authy.login`, `authy.register`, `authy.unregister`, `authy.remember`, `authy.pin`
