### ISSUE TITLE
Suggestion for Before login disable message event

### ISSUE THREAD

**Issue by LoneDevilX** [Iru21/Authy#31]
Hi there author, i notice people can chat before they login, actually there are some hackers sendhack code thru chat to obtain op/ backend commands. Could you please verify on this allow us to disable login chat event.

![image](https://user-images.githubusercontent.com/67851836/226119510-445d34da-f405-4d00-a5fc-9892dee1a8bb.png)

**Comment by Iru21** [comment]
chat is already being blocked, must be a plugin conflict

**Comment by Iru21** [comment]
accidentally closed this, do you have any plugins that may modify chat messages?
