### ISSUE TITLE
Please give him an administrator to reset the password

### ISSUE THREAD

**Issue by aml2023529** [Iru21/Authy#37]
Can I give instructions for plugin optimization? help can display the command of this plugin like AuthMe, please add for the administrator to reset the player password pin, now my player forgot the password can not find the method, there are other features such as broadcast login success after the middle display login success large font can be set in the configuration file to close or open for people who need and do not need

**Comment by Iru21** [comment]
I did not understand a thing from your suggestion, join the [discord support server](https://discord.gg/jrebrmDD5X) and explain it better there. As for when someone forgets their password use `unregister [username]` in the console

**Comment by aml2023529** [comment]
I mean /authy help shows the commands that the plugin has because I can't remember them

**Comment by aml2023529** [comment]
Sorry, I am from China. My worst thing is that I can only rely on translators to communicate in English
