### ISSUE TITLE
Repeated reconnection removes protections

### ISSUE THREAD

**Issue by umioMikket** [Iru21/Authy#48]
With multiple quick logins and logouts, after 7-15 times no password is required! As an admin, I was hacked! VERSION LAST

**Comment by Limeen** [comment]
I just tested and i confirm, i can reproduce the bug
The temporary solution is to set a timer before reconnecting again.

**Comment by Iru21** [comment]
Try testing with build from #49, download the built artifact [here](https://github.com/Iru21/Authy/actions/runs/6518340660?pr=49)
