### ISSUE TITLE
Can we see the passwords ?

### ISSUE THREAD

**Issue by Ocpkayp6662** [Iru21/Authy#67]
Hello my friend stoped playing and we want the get his items is there any way to see password from the server folder or anyway the remove the password

**Comment by ItsMeRomian** [comment]
No, there is no way to view the password in plaintext. You can reset your friends account with `/unregister <username>` in the console or by someone with `authy.unregister` permission.

**Comment by ahaququq** [comment]
https://iotools.cloud/tool/sha256-decrypt/ here you go
